[build]
  command = """
    python -m pip install --upgrade pip
    pip install -r requirements.txt --no-cache-dir
  """
  publish = "."

[build.environment]
  NODE_VERSION = "16.14.0"
  PYTHON_VERSION = "3.8.10"
